filebeat.inputs:
  - input_type: log
    paths:
      - /home1/irteam/logs/access.log
    fields:
      log_type: accesslog
    fields_under_root: true
  - input_type: log
    paths:
      - /home1/irteam/logs/app.log
    fields:
      log_type: applog
    fields_under_root: true
output.logstash:
  hosts: [ "localhost:5044" ]
